name: 'Update Kubernetes Manifest'
description: 'Updates image tags in Kubernetes manifest and commits changes'
inputs:
  manifest_repo:
    description: 'Manifest repository (e.g., owner/repo)'
    required: true
  manifest_ref:
    description: 'Manifest repository branch'
    required: true
  manifest_path:
    description: 'Path to manifest file (or comma-separated paths)'
    required: true
  service_name:
    description: 'Service name in manifest'
    required: true
  image_tag:
    description: 'New image tag'
    required: true
  git_pat:
    description: 'GitHub PAT for manifest repo access'
    required: true
  commit_message:
    description: 'Git commit message'
    required: false
    default: 'Update image tags'
  migrate_service_name:
    description: 'Migration service name (optional). Use "default" for migrate.image.tag structure, or specific name for migrate.<name>.image.tag'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout manifest repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.manifest_repo }}
        path: manifests
        token: ${{ inputs.git_pat }}
        ref: ${{ inputs.manifest_ref }}

    - name: Update image tags
      shell: bash
      run: |
        cd manifests
        SERVICE_NAME="${{ inputs.service_name }}"
        IMAGE_TAG="${{ inputs.image_tag }}"
        MIGRATE_SERVICE_NAME="${{ inputs.migrate_service_name }}"

        IFS=',' read -ra MANIFEST_PATHS <<< "${{ inputs.manifest_path }}"
        for path in "${MANIFEST_PATHS[@]}"; do
          trimmed_path=$(echo "$path" | xargs)

          # Check if file exists
          if [ ! -f "$trimmed_path" ]; then
            echo "❌ File not found: $trimmed_path"
            exit 1
          fi

          echo "📝 Updating $trimmed_path"
          echo "   Service: $SERVICE_NAME"
          echo "   Tag: $IMAGE_TAG"

          # Update service image tag
          yq eval ".services.\"$SERVICE_NAME\".image.tag = \"$IMAGE_TAG\"" -i "$trimmed_path"

          # Update migrate image tag if migrate service name provided
          if [ -n "$MIGRATE_SERVICE_NAME" ]; then
            if [ "$MIGRATE_SERVICE_NAME" = "default" ]; then
              # Support old structure: migrate.image.tag
              echo "   Migrate: default structure (migrate.image.tag)"
              yq eval ".migrate.image.tag = \"$IMAGE_TAG\"" -i "$trimmed_path"
            else
              # Support new structure: migrate.<serviceName>.image.tag
              echo "   Migrate service: $MIGRATE_SERVICE_NAME"
              yq eval ".migrate.$MIGRATE_SERVICE_NAME.image.tag = \"$IMAGE_TAG\"" -i "$trimmed_path"
            fi
          fi

          echo "✅ Updated: $trimmed_path"
        done

        # Show git diff to verify changes
        echo ""
        echo "📋 Changes made:"
        git diff

    - name: Commit and push with retry
      shell: bash
      run: |
        cd manifests
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .

        # Check if there are changes to commit
        if git diff --cached --quiet; then
          echo "⚠️ No changes to commit - manifest already up to date"
          exit 0
        fi

        git status
        git commit -m "${{ inputs.commit_message }}"

        # Retry logic with pull-rebase to handle concurrent pushes
        max_retries=5
        retry_count=0

        while [ $retry_count -lt $max_retries ]; do
          if git push; then
            echo "✅ Push successful"
            exit 0
          else
            echo "⚠️ Push failed, attempt $((retry_count + 1))/$max_retries"
            retry_count=$((retry_count + 1))

            if [ $retry_count -lt $max_retries ]; then
              # Pull with rebase to get remote changes
              git pull --rebase origin ${{ inputs.manifest_ref }}

              # Small random delay to avoid thundering herd
              sleep $((RANDOM % 5 + 1))
            fi
          fi
        done

        echo "❌ Failed to push after $max_retries attempts"
        exit 1
